name: Chess
version: 1.0.0
author: Apollo
main: com.apollo.chess.ChessMain
api-version: 1.18
commands:
  startChess:
    description: This commands starts chess
  movePiece:
    description: This commands starts chess
  selectSquare:
    description: Highlights available squares